# Based on https://github.com/actions/starter-workflows/blob/ebda693bc06206f7a6706a7c8c786b9ca5e6e4b6/ci/node.js.yml

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - run: yarn test
    - run: yarn test -- --coverage-report=text-lcov | yarn codecov --pipe
